Update toh-pt5.md
han41858/angular-ko pull request #56
Opened 2020-08-27 05:40 UTC by funnystyle

번역되지 않은 문장을 번역함

## 목적
- [ v ] 번역 오류 수정
- [ ] 오타 수정
- [ ] 사이트 오류 수정

2020-08-27 08:10 UTC, han41858 approved these changes

2020-08-27 08:29 UTC, han41858 requested changes
번역이 누락된 문장이 있었네요.. ㅎ
그런데 원문의 맥락이 좀 이상해서 이렇게 변경하는 것은 어떨까요?

이전 섹션에서 로드했던 `HeroesComponent`를 라우팅 규칙으로 등록하려면 `routes` 배열을 다음과 같이 작성하면 됩니다:

2020-08-28 07:18 UTC, funnystyle commented
네 어떻게 번역하든 상관 없습니다. 그저, 번역 안된 문장이 눈에 띄었을 뿐이에요. 
예전에 원문으로 보았던 튜토리얼을 급하게 리마인드해야할 상황이었는데
번역된 사이트가 있어서 아주 쉽게 보았습니다.
이 자릴 빌어 힘든 작업 해주신 것 감사드립니다.

> 번역이 누락된 문장이 있었네요.. ㅎ
> 그런데 원문의 맥락이 좀 이상해서 이렇게 변경하는 것은 어떨까요?
> 
> 이전 섹션에서 로드했던 `HeroesComponent`를 라우팅 규칙으로 등록하려면 `routes` 배열을 다음과 같이 작성하면 됩니다:

2020-08-28 15:02 UTC, merged

2020-08-28 15:04 UTC, han41858 commented
안녕하세요. 한장현입니다.

해당 문장은 말씀드린 대로 수정했고, 그 앞 문단 문장도 어색한 부분이 있어서 함께 수정했습니다.
다만, 도움을 주신 부분을 살리고자 mr 후 추가 수정하는 방식으로 진행했습니다.

오류를 찾아주시고 적절하게 수정할 수 있도록 제안도 해주셔서 정말 감사드립니다. :)